### ISSUE TITLE
cv.vip less then number of variables ?

### ISSUE THREAD

**Issue by 809825706** [DongElkan/pypls#9]
![image](https://github.com/user-attachments/assets/21effdc7-a0ac-47a1-819d-aecfb2710349)

**Comment by DongElkan** [comment]
This is probably because some of the variables have unique values, so in the analysis, they will be removed as they will corrupt the standardisation of variables. So please go to `cv.used_variable_index` to check which variable is excluded.

**Comment by 809825706** [comment]
That's strange. They're not unique.

**Comment by 809825706** [comment]
> That's strange. They're not unique.

![2024-12-03 13-16-42屏幕截图](https://github.com/user-attachments/assets/d7ce9589-db7f-4efd-ad68-4e353caeccf1)

**Comment by 809825706** [comment]
> > That's strange. They're not unique.
> 
> ![2024-12-03 13-16-42屏幕截图](https://private-user-images.githubusercontent.com/46601791/391830736-d7ce9589-db7f-4efd-ad68-4e353caeccf1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM0MDE0MTIsIm5iZiI6MTczMzQwMTExMiwicGF0aCI6Ii80NjYwMTc5MS8zOTE4MzA3MzYtZDdjZTk1ODktZGI3Zi00ZWZkLWFkNjgtNGUzNTNjYWVjY2YxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA1VDEyMTgzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgzYTc4YzFiODZkMDEyZjNhOTc4MjFkYTJjYjgzNTM2NWE1Nzk1NDNlMDQ1M2E5YzYyMDEwZjhkY2ZiNTYyMWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.vPMwsJ6_xWjsMezw19TXaxOEAra7U0JN4VEddkuq83Q)

I seem to know why. The data accepted by the function doesn't need to be normalised in advance, right?

**Comment by 809825706** [comment]
I compared with the results from ropls using the example data. there seems some different? how to get the percent of T1？

from ropls：

![image](https://github.com/user-attachments/assets/0d59001d-94da-418c-a448-0c502a889f15)

from pypls：

![image](https://github.com/user-attachments/assets/5159f942-7dfc-4390-9ed1-56042016b354)

**Comment by DongElkan** [comment]
> > > That's strange. They're not unique.
> > 
> > 
> > ![2024-12-03 13-16-42屏幕截图](https://private-user-images.githubusercontent.com/46601791/391830736-d7ce9589-db7f-4efd-ad68-4e353caeccf1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM0MDE0MTIsIm5iZiI6MTczMzQwMTExMiwicGF0aCI6Ii80NjYwMTc5MS8zOTE4MzA3MzYtZDdjZTk1ODktZGI3Zi00ZWZkLWFkNjgtNGUzNTNjYWVjY2YxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA1VDEyMTgzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgzYTc4YzFiODZkMDEyZjNhOTc4MjFkYTJjYjgzNTM2NWE1Nzk1NDNlMDQ1M2E5YzYyMDEwZjhkY2ZiNTYyMWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.vPMwsJ6_xWjsMezw19TXaxOEAra7U0JN4VEddkuq83Q)
> 
> I seem to know why. The data accepted by the function doesn't need to be normalised in advance, right?

Yes, it should be specified during cross validation.

To calculate the variance contribution of `t_p`, use:

1. calculate the variance of data matrix: `cov_x = ((x - x.mean(axis=0)) ** 2).sum()`
2. estimate the percentage: `(cv.scores ** 2).sum() / cov_x`
